name: fizzy_api
description: "A lightweight, structured wrapper around dio that simplifies Flutter API calls with minimal boilerplate and easy customization."

repository: 'https://github.com/Sourabh8432/fizzyApi.git'
homepage: 'https://thessk.in'
version: 0.0.2

license: "MIT"

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.8.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

social:
  linkedin: "https://www.linkedin.com/in/ssk84/"
  github: "https://github.com/Sourabh8432"

example:
  - example/lib/main.dart

keywords:
  - flutter
  - fizzy_api
  - dio
  - api
  - wrapper
  - rest-api
  - package
  - flutter-package
  - flutter-dio