name: fizzy_api
description: "A lightweight and structured wrapper over the `dio` package to simplify API calls in Flutter. `fizzy_api` provides a clean and organized way to make REST API requests with minimal boilerplate and easy customization."

repository: ''
homepage: ''
version: 0.0.1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.8.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
